#!/bin/bash

##########################################################################
# The MIT License (MIT)                                                  #
#                                                                        #
# Copyright (c) 2014 Foivos S. Zakkak <foivos@zakkak.net>                #
#                                                                        #
# Permission is hereby granted, free of charge, to any person obtaining  #
# a copy of this software and associated documentation files (the        #
# "Software"), to deal in the Software without restriction, including    #
# without limitation the rights to use, copy, modify, merge, publish,    #
# distribute, sublicense, and/or sell copies of the Software, and to     #
# permit persons to whom the Software is furnished to do so, subject to  #
# the following conditions:                                              #
#                                                                        #
# The above copyright notice and this permission notice shall be         #
# included in all copies or substantial portions of the Software.        #
#                                                                        #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        #
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     #
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND                  #
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE #
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION #
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION  #
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.        #
##########################################################################

##########################################################################
#                                                                        #
# Extracts all turnins in the current directory in subfolders named      #
# after the name of the tgz, i.e., csdXXXX.tgz will be extracted in      #
# a folder named csdXXXX                                                 #
#                                                                        #
# (DO NOT USE under ~class/TURNIN/)                                      #
#                                                                        #
##########################################################################

# Extract them
for i in *.tgz
do
    login=${i%.tgz};
    mkdir -p $login;
    tar -C $login -xzf $i;
done

# Replace spaces with underscores in the filenames/paths
find . -name "* *"| while read i
do
    mv "$i" `echo $i| tr ' ' '_'`
done

# decompress any compressed files (this is possible to be submitted if
# binary is enabled)
find . -name "*.rar"| while read i
do
    curr=`pwd`
    cd $(dirname $i)
    unrar x $(basename $i)
    rm $(basename $i)
    cd $curr
done

find . -name "*.tar.*"| while read i
do
    curr=`pwd`
    cd $(dirname $i)
    tar xf $(basename $i)
    rm $(basename $i)
    cd $curr
done

find . -name "*.zip"| while read i
do
    curr=`pwd`
    cd $(dirname $i)
    unzip $(basename $i)
    rm $(basename $i)
    cd $curr
done
